name: dartist
version: 0.0.2
author: Duvo <noemi.salaun@gmail.com>
description: Simple Dart web server.
homepage: https://github.com/Duvo/Dartist
dependencies:
  mustache: any
  route: any
  stream: any
dev_dependencies:
  browser: any
  crypto: any
  http: any
  unittest: any
