name: dartist
version: 0.1.0
author: Duvo <noemi.salaun@gmail.com>
description: Simple Dart web server.
homepage: https://github.com/Duvo/Dartist
dependencies:
  route: '>=0.4.5 <=0.4.5'
dev_dependencies:
  args: any
  browser: any
  crypto: any
  http: any
  unittest: any

#dependencies:
#  unittest: any